config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'list', to: 'posts#list'
  root to: 'posts#index'
  resources :posts
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :description
    extend FriendlyId
    friendly_id :title, use: :slugged

    def should_generate_new_friendly_id?
        title_changed?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/list
  def list
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update 
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
    <div class="collapse-bg p-a-1">
        <div class='card'>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <%= link_to 'Create', root_path, class: "nav-link #{yield(:create_active)}"%>
                </li>
                <li class="list-group-item">
                    <%= link_to 'Edit', root_path, class: "nav-link #{yield(:edit_active)}"%>
                </li>
                <li class="list-group-item">
                    <%= link_to 'Delete', root_path, class: "nav-link #{yield(:delete_active)}"%>
                </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Portfolio </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container <%= controller_name %> <%= action_name %>">

    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <td><%= link_to 'Create Project', new_post_path %></td> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> |
        <%= link_to "Home", root_path, :class => 'navbar-link' %> |
      <% else %>
        <%= link_to "sign up", new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Login", new_user_registration_path, :class => 'navbar-link' %>
      <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%=notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<!doctype html>
<html lang="en">

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <p><%= button_to "Home", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Index", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
        </ul>
      </div>
    </nav>
    <h0>Show Project</h0>
    <h1>Edit Project</h1>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"></h1>
          <p>Edit your project by filling out the following.</p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <%= render 'form', post: @post %>
            <%= link_to 'Show', @post %> |
            <%= link_to 'Back', posts_path %>
          </div>
          <div class="col-md-4">
            <h2><strong><%= current_user.email %></strong></h2>
            <img class="rounded-circle float-right img-thumbnail" style="width:25%" src="https://pathfindercareers.com/wp-content/uploads/2019/06/poop.jpeg" data-holder-rendered="true"
          </div>

        </div>

        <hr>

      </div> <!-- /container -->

    </main>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    
  </body>
  
  </head>

    
</html>

app/views/posts/index.html.erb
<% provide(:page_title, 'Projects') %>

<p id="notice"><%= notice %></p>




<!doctype html>
<html lang="en">
  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <p><%= button_to "Home", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Index", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Portfolio</h1>
          <p>Some stuff about the Portfolio owner goes here!.</p>
          <h2><strong><%= current_user.email %></strong></h2>
          <img class="rounded-circle float-right img-thumbnail" style="width:25%" src="https://pathfindercareers.com/wp-content/uploads/2019/06/poop.jpeg" data-holder-rendered="true"
          <p><%= button_to "Learn More", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-5">
            <h2>Projects</h2>
            <p>
              <table>
              <thead>
                <tr>
                  <th>Project Titles:</th>
                  <tbody>
                  <% @posts.each do |post| %>
                    <tr>
                      <td><%= post.title %></td>
                      <td><%= post.description %></td>
                      <td><%= link_to 'Show|', post %></td>
                      <% if user_signed_in? %>
                        <td><%= link_to 'Edit|', edit_post_path(post) %></td>
                        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </p>
          </div>
          <div class="col-md-4">
            <h2>Create New Project</h2>
            <p><%= button_to "New Project", new_post_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </div>

        </div>

        <hr>

      </div> <!-- /container -->

    </main>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    
  </body>
  
  </head>

    
</html>
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

<title>Jumbotron Template for Bootstrap</title>

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

<!-- Bootstrap core CSS -->
<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="jumbotron.css" rel="stylesheet">
</head>

app/views/posts/list.html.erb
<% provide(:page_title, 'Projects') %>

<p id="notice"><%= notice %></p>

<h1>Projects</h1>
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<!doctype html>
<html lang="en">

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <p><%= button_to "Home", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Index", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
        </ul>
      </div>
    </nav>
    <h0>Show Project</h0>
    <h1>New Project</h1>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"></h1>
          <p>Create a new project by filling out the following.</p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Create New Project</h2>
            <%= render 'form', post: @post %>

            <%= link_to 'Back', posts_path %>
          </div>
          <div class="col-md-4">
            <h2><strong><%= current_user.email %></strong></h2>
            <img class="rounded-circle float-right img-thumbnail" style="width:25%" src="https://pathfindercareers.com/wp-content/uploads/2019/06/poop.jpeg" data-holder-rendered="true"
          </div>

        </div>

        <hr>

      </div> <!-- /container -->

    </main>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    
  </body>
  
  </head>

    
</html>

app/views/posts/show.html.erb
<!doctype html>
<html lang="en">
  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <p><%= button_to "Home", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></p>
          </li>
          <li class="nav-item">
          <p><%= button_to "Index", root_path, :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %></p>
          </li>
        </ul>
      </div>
    </nav>
    <h0>Show Project</h0>
    <h1>Show Project</h1>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"></h1>
          <p>Edit your project by filling out the following.</p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Project Details</h2>
              <% provide(:page_title, @post.title) %>

              <p id="notice"><%= notice %></p>

              <p>
                <strong>Title:</strong>
                <%= @post.title %>
              </p>

              <p>
                <strong>Body:</strong>
                <%= @post.body %>
              </p>

              <p>
                <strong>Description:</strong>
                <%= @post.description %>
              </p>


              <%= link_to 'Edit', edit_post_path(@post) %> |
              <%= link_to 'Back', posts_path %>
          </div>
          <div class="col-md-4">
            <h2><strong><%= current_user.email %></strong></h2>
            <img class="rounded-circle float-right img-thumbnail" style="width:25%" src="https://pathfindercareers.com/wp-content/uploads/2019/06/poop.jpeg" data-holder-rendered="true"
          </div>

        </div>

        <hr>

      </div> <!-- /container -->

    </main>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    
  </body>
  
  </head>

    
</html>